- name: variables in ansible
  hosts: mongodb
  # this is play level variables, map
  vars:
    course: devops
    trainer: siva
    duration: 110hrs
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "hello, i am learning ansible"
  - name: print variables
    ansible.builtin.debug:
      msg: "hello, i am learning {{course}}, trainer is {{trainer}}, duration is {{duration}}"    