- name: variables at task level
  hosts: localhost
  # these variables are parent or play level
  vars:
  - money: "1000 RS"
    land: "1 hectar"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add and override
    vars:
    - money: "2000 RS"
      houses: "4 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"        