- name: testing variable procedure
  hosts: mongodb
  vars:
    NAME: aparna-play
 # vars_files:
 # - variables.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: please enter Trainer Name
  #   private: false
  tasks: 
  - name: variable at task level
    ansible.builtin.debug:
      msg: "trainer name is: {{NAME}}" 

 # 1. command line variables.
 # 2. task level  
 # 3. vars_files  
 # 4. prompt    